project:
  type: book

book:
  title: "CS 1840: Introduction to Reinforcement Learning"
  author: "Alexander Cai"
  date: "2025-01-03"
  chapters:
    - index.qmd
    - mdps.qmd
    - control.qmd
    - bandits.qmd
    - supervised_learning.qmd
    - fitted_dp.qmd
    - pg.qmd
    - imitation_learning.qmd
    - planning.qmd
    - exploration.qmd
  appendices:
    - background.qmd
    - proofs.qmd
    - references.qmd

bibliography: references.bib
csl: apa.csl

resources:
  - CNAME

crossref:
  eq-prefix: "eq."
  exm-prefix: "ex."
  fig-prefix: "fig."
  tbl-prefix: "tbl."
  sec-prefix: "sec."
  def-prefix: "def."

format:
  html:
    theme: cosmo
    code-fold: true
    fig-width: 4
    fig-height: 3
  pdf:
    documentclass: scrreprt
    echo: false



