# Acknowledgements {.unnumbered}

This work would not have been possible without the patient guidance of my advisor,
Professor Lucas Janson.
Thank you for your advice on drafts
and your time spent bringing this project to life
in the midst of your happy responsibilities.

I shall be eternally grateful to the faculty mentors
who have guided my journey as an undergraduate researcher.
Thank you, Professor Janson and Professor Sham Kakade,
for bringing a course on reinforcement learning to Harvard
and for inviting me as an undergraduate course assistant.
I hope this work is faithful
in conveying your deep insights
in statistics and machine learning
and passing on your vibrant curiosity.
Thank you, Professor Cengiz Pehlevan,
for teaching my favourite course, APMTH 226,
and for your unwavering encouragement as a research mentor.
Thank you, Professor Sarah Dean,
for trialling a draft of this textbook for your Introduction to Reinforcement Learning course at Cornell.
To the TAs and students thereof,
thank you as well for your patience and helpful feedback.

To the "daniel wang" blocking group,
Gabe, Oliver, Eric, Nick, Joel, Ezra, and Yusuf,
thank you for your friendship these four years.
I count it as a miracle to have my life illuminated by your brightness
in this time when kindness seems to be running scarce in our world.
Conversations with you have opened my mind
in ways that no course assignment ever could.

Thank you to Currier for feeling like home.
Jack, Jess, Jocelyn, Jude, Kelly, Kenny, Kyra, Luke, Madison, Rave, Rick, Sarah,
I am so blessed to be in your company.
I cannot wait, years down the line,
to point in the news and tell people "Hey, I was their friend!"

Thank you, Daniel, for being the Glinda to my Elphaba.
I simply couldn't be happier.
Thank you for being the city on a hill
that led me back to to who I am.

I am deeply grateful to the AI Safety Student Team (formerly HAIST)
for daring to save the world.
I constantly look up to the ambition, courage, and agency
of all the students in this group.
Thank you also to the Harvard Undergraduate Machine Intelligence Community
for giving me the chance to showcase my tree-punching Minecraft agent in freshman year.
Jason, Samantha, and Helen,
your leadership and fortitude astound me.

My greatest thanks goes to the students of CS 184(0).
Thank you for daring to take this challenging course
and for leaving us your (sometimes brutally) honest feedback.
I was truly inspired by the ambition of your diverse projects
and the diligence in your studies.
Thank you to my fellow teaching staff across all three years
for listening to students and making the course possible.
