###############################################################################
# Auto-generated by `jupyter-book config`
# If you wish to continue using _config.yml, make edits to that file and
# re-generate this one.
###############################################################################
author = 'Alexander D. Cai'
bibtex_bibfiles = ['shared/references.bib']
bibtex_reference_style = 'author_year'
comments_config = {'hypothesis': False, 'utterances': {'repo': 'adzcai/cs-stat-184-notes'}}
copyright = '2023'
exclude_patterns = ['**.ipynb_checkpoints', '.DS_Store', 'Thumbs.db', '_build']
extensions = ['sphinx_togglebutton', 'sphinx_copybutton', 'myst_nb', 'jupyter_book', 'sphinx_thebe', 'sphinx_comments', 'sphinx_external_toc', 'sphinx.ext.intersphinx', 'sphinx_design', 'sphinx_book_theme', 'sphinx_proof', 'sphinxcontrib.bibtex', 'sphinx_jupyterbook_latex', 'sphinx_multitoc_numbering']
external_toc_exclude_missing = True
external_toc_path = '_toc.yml'
html_baseurl = ''
html_favicon = ''
html_logo = 'shared/184.png'
html_sourcelink_suffix = ''
html_theme = 'sphinx_book_theme'
html_theme_options = {'search_bar_text': 'Search this book...', 'launch_buttons': {'notebook_interface': 'classic', 'binderhub_url': '', 'jupyterhub_url': '', 'thebe': False, 'colab_url': ''}, 'path_to_docs': 'book', 'repository_url': 'https://github.com/adzcai/cs-stat-184-notes', 'repository_branch': 'main', 'extra_footer': '', 'home_page_in_toc': False, 'announcement': '', 'analytics': {'google_analytics_id': ''}, 'use_repository_button': False, 'use_edit_page_button': False, 'use_issues_button': False}
html_title = 'CS/STAT 184: Introduction to Reinforcement Learning'
latex_elements = {'pointsize': '12pt', 'preamble': '\\let\\P\\undefined\n\\DeclareMathOperator*{\\E}{\\mathbb{E}}\n\\DeclareMathOperator*{\\P}{\\mathbb{P}}\n\\newcommand{\\hi}{h}\n\\newcommand{\\hor}{H}\n\\newcommand{\\st}{s}\n\\newcommand{\\act}{a}\n\\newcommand{\\kl}[2]{\\mathrm{KL}\\left(#1 \\parallel #2\\right)}\n'}
latex_engine = 'pdflatex'
mathjax3_config = {'tex': {'macros': {'E': '\\mathop{\\mathbb{E}}', 'P': '\\mathop{\\mathbb{P}}', 'hi': 'h', 'hor': 'H', 'st': 's', 'act': 'a', 'kl': ['\\mathrm{KL}\\left(#1 \\parallel #2\\right)', 2]}}}
mathjax_path = 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js'
myst_enable_extensions = ['colon_fence', 'dollarmath', 'linkify', 'substitution', 'tasklist']
myst_url_schemes = ['mailto', 'http', 'https']
nb_execution_allow_errors = False
nb_execution_cache_path = ''
nb_execution_excludepatterns = []
nb_execution_in_temp = False
nb_execution_mode = 'cache'
nb_execution_timeout = 30
nb_output_stderr = 'show'
numfig = True
pygments_style = 'sphinx'
suppress_warnings = ['myst.domains']
use_jupyterbook_latex = True
use_multitoc_numbering = True
